using Stratus.Events;

namespace Stratus.Models.Audio
{
	/// <summary>
	/// The default audio channels considered by this model.
	/// </summary>
	public enum DefaultAudioChannel
	{
		/// <summary>
		/// Background audio, such as music
		/// </summary>
		Background,
		/// <summary>
		/// Environmental sound
		/// </summary>
		Ambient,
		/// <summary>
		/// Sound effects, generated by objects in the game
		/// </summary>
		Effect,
		/// <summary>
		/// Voices
		/// </summary>
		VoiceOver
	}

	public abstract class AudioEvent : Event
	{
		/// <summary>
		/// The channel being targeted
		/// </summary>
		public DefaultAudioChannel channel { get; }

		/// <summary>
		/// The fade duration
		/// </summary>
		public float duration { get; }

		protected AudioEvent(DefaultAudioChannel channel)
		{
			this.channel = channel;
		}
	}

	// TODO: Better name
	/// <summary>
	/// Play the given audio track
	/// </summary>
	public class PlayAudioEvent : AudioEvent
	{
		/// <summary>
		/// The name of the track to play
		/// </summary>
		public string name { get; }

		public PlayAudioEvent(DefaultAudioChannel channel, string name)
			: base(channel)
		{
			this.name = name;
		}
	}

	/// <summary>
	/// Stops playback on the given channel
	/// </summary>
	public class StopAudioEvent : AudioEvent
	{
		public StopAudioEvent(DefaultAudioChannel channel) : base(channel)
		{
		}
	}
}
