using Stratus.Events;

namespace Stratus.Models.Audio
{
	public abstract class Soundtrack<TAsset> where TAsset : class
	{
	}

	public enum AudioChannelType
	{
		/// <summary>
		/// Background audio, such as music
		/// </summary>
		Background,
		/// <summary>
		/// A track for the environment
		/// </summary>
		Ambient,
		/// <summary>
		/// Sound effects, generated by objects in the game
		/// </summary>
		Effect,
		/// <summary>
		/// Voices
		/// </summary>
		VoiceOver
	}

	// TODO: Better name
	public class PlayAudioEvent : Event
	{
		/// <summary>
		/// The name of the track to play
		/// </summary>
		public string name { get; }
		/// <summary>
		/// 
		/// </summary>
		public AudioChannelType channel { get; }
	}
}
